In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
series_obj = Series(np.arange(8),index=['row 1', 'row 2','row 3','row 4','row 5','row 6','row 7','row 8'])
np.random.seed(25)
DF_obj = DataFrame(np.random.rand(36).reshape((6,6)),index=['row 1','row 2','row 3','row 4','row 5','row 6'],
                  columns=['column 1','column 2','column 3','column 4','column 5','column 6'])

In [7]:
series_obj < 4

row 1     True
row 2     True
row 3     True
row 4     True
row 5    False
row 6    False
row 7    False
row 8    False
dtype: bool

In [8]:
series_obj[series_obj < 4]

row 1    0
row 2    1
row 3    2
row 4    3
dtype: int64

In [4]:
DF_obj

       column 1  column 2  column 3  column 4  column 5  column 6
row 1  0.870124  0.582277  0.278839  0.185911  0.411100  0.117376
row 2  0.684969  0.437611  0.556229  0.367080  0.402366  0.113041
row 3  0.447031  0.585445  0.161985  0.520719  0.326051  0.699186
row 4  0.366395  0.836375  0.481343  0.516502  0.383048  0.997541
row 5  0.514244  0.559053  0.034450  0.719930  0.421004  0.436935
row 6  0.281701  0.900274  0.669612  0.456069  0.289804  0.525819

In [5]:
DF_obj < .2

       column 1  column 2  column 3  column 4  column 5  column 6
row 1     False     False     False      True     False      True
row 2     False     False     False     False     False      True
row 3     False     False      True     False     False     False
row 4     False     False     False     False     False     False
row 5     False     False      True     False     False     False
row 6     False     False     False     False     False     False