In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
DF_obj = DataFrame({'column 1': [1, 1, 2, 2, 3, 3, 3],
                  'column 2': ['a', 'a', 'b', 'b', 'c', 'c', 'c'],
                  'column 3': ['A', 'A', 'B', 'B', 'C', 'C', 'C']})
DF_obj

   column 1 column 2 column 3
0         1        a        A
1         1        a        A
2         2        b        B
3         2        b        B
4         3        c        C
5         3        c        C
6         3        c        C

In [3]:
series_obj = Series([1,2,2,3,1,4,2,3,1])
series_obj

0    1
1    2
2    2
3    3
4    1
5    4
6    2
7    3
8    1
dtype: int64

In [4]:
series_obj.duplicated()

0    False
1    False
2     True
3    False
4     True
5    False
6     True
7     True
8     True
dtype: bool

In [5]:
DF_obj.duplicated()

0    False
1     True
2    False
3     True
4    False
5     True
6     True
dtype: bool

In [6]:
series_obj.drop_duplicates()

0    1
1    2
3    3
5    4
dtype: int64

In [7]:
DF_obj.drop_duplicates()

   column 1 column 2 column 3
0         1        a        A
2         2        b        B
4         3        c        C

In [9]:
DF_obj.drop_duplicates('column 2')

   column 1 column 2 column 3
0         1        a        A
2         2        b        B
4         3        c        C